#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

export LANG='en_AU.utf8'
export LC_CTYPE='en_AU.UTF-8'
#export LC_CTYPE=C

export MAIL=/var/mail/$USER

# Preferred editor for local and remote sessions
# if [[ -n $SSH_CONNECTION ]]; then
#     export EDITOR='vim'
# else
#     export EDITOR=emacsclient
#     export ALTERNATE_EDITOR=emacs
# fi
export VISUAL=emacsclient
export EDITOR=emacsclient
export ALTERNATE_EDITOR=emacs

export MANWIDTH=96

export TERM=xterm-256color
[ -n "$DISPLAY" ] && export TERM=xterm-256color
[ -n "$TMUX" ] && export TERM=screen-256color
[ -n "$BYOBU_BACKEND" ] && export TERM=screen-256color
[ -n "$INSIDE_EMACS" ] && export TERM=eterm-color

autoload -U colors
colors

# Recent versions of Fedora have renamed qmake.
if grep -iq 'id=fedora' /etc/os-release; then
  export QMAKE=/usr/bin/qmake-qt4
fi

# Work around for Google Chrome not accepting keyboard input in addressbar
# https://bugs.launchpad.net/ubuntu/+source/chromium-browser/+bug/1307648
export GTK_IM_MODULE=ibus
export QT_IM_MODULE=ibus
export CLUTTER_IM_MODULE=ibus

if [ -f "$HOME/.zsh-aliases" ]; then
  source $HOME/.zsh-aliases
fi

if [ -f "$HOME/.zsh-funcs" ]; then
  source $HOME/.zsh-funcs
fi

if [[ -f "$HOME/.aws_keys" ]]; then
  source "$HOME/.aws_keys";
fi

export DEFAULT_USER=colbell

# Emacs seems to need a trailing : character on the path otherwise
# it ignores the value of $PATH and just uses the standard system path.
# export PATH="$PATH:"

# export PATH="$PATH:$HOME/.rvm/bin" # Add RVM to PATH for scripting
